version: '3.8'

services:
  hotscan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotscan
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - PROBEX_API_KEY=${PROBEX_API_KEY}
      - AIUM_API_KEY=${AIUM_API_KEY}
      - CHATAIAPI_KEY=${CHATAIAPI_KEY}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JOB_TOKEN=${JOB_TOKEN}
      - DATASOURCE=${DATASOURCE}
      - NEXT_PUBLIC_HOMEPAGE_REFRESH_INTERVAL_MS=${NEXT_PUBLIC_HOMEPAGE_REFRESH_INTERVAL_MS}
    networks:
      - hotscan-network

networks:
  hotscan-network:
    driver: bridge
